@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

TripLog *-right-> "1" UniqueTripList
UniqueTripList -right-> "*" Trip

Trip *-up-> "*" Tag

Trip *--> "1" Name
Trip *--> "0..1" Phone
Trip *--> "0..1" Email
Trip *--> "0..1" Address
Trip *--> "0..2" TripDate
@enduml
