@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Logic {
    Class ListCommand
    Class ListCommandParser
}

package Model {
    Class Trip
}

Class "<<interface>>\nComparator" as Comparator {
    +compare(t1: Trip, t2: Trip): int
}

Class NameComparator
Class DateComparator
Class DurationComparator

ListCommandParser .down.> ListCommand : <<create>>
ListCommand .down.> Comparator : <<use factory>>

NameComparator .up.|> Comparator
DateComparator .up.|> Comparator
DurationComparator .up.|> Comparator

ListCommand -[hidden]right-> Trip
Comparator .right.> Trip : <<compares>>
@enduml
